-- Create a table for consultations
CREATE TABLE consultations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name TEXT NOT NULL,
    dob TEXT NOT NULL,
    tob TEXT NOT NULL,
    pob TEXT NOT NULL,
    phone TEXT NOT NULL,
    question TEXT NOT NULL,
    consent_accepted BOOLEAN NOT NULL,
    status TEXT DEFAULT 'Pending' CHECK (status IN ('Pending', 'Done')),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Set up Row Level Security (RLS)
ALTER TABLE consultations ENABLE ROW LEVEL SECURITY;

-- Allow public inserts
CREATE POLICY "Allow public inserts" ON consultations
    FOR INSERT WITH CHECK (true);

-- Allow public read (for admin panel, simplified for now since auth is handled client-side)
-- For production, this should be restricted to authenticated admin users only via Supabase Auth
CREATE POLICY "Allow public select" ON consultations
    FOR SELECT USING (true);

-- Allow public updates (for admin panel)
CREATE POLICY "Allow public update" ON consultations
    FOR UPDATE USING (true);

-- Allow public deletes (for admin panel)
CREATE POLICY "Allow public delete" ON consultations
    FOR DELETE USING (true);
